name: Deploy Backend
on:
  push:
    paths: ['backend/**']
    branches: [main]
  pull_request:
    paths: ['backend/**']
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Deploy
        uses: cloudflare/wrangler-action@v3.12.0
        with:
          workingDirectory: backend
          packageManager: pnpm
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: deploy --minify
